//constants.ts
import { IconType } from 'react-icons';
import { 
  FaHardHat, 
  FaShip, 
  FaBox, 
  FaCalendarAlt, 
  FaChartBar, 
  FaUser, 
  FaSignOutAlt, 
  FaTimes,
  FaExclamationTriangle,
  FaCheckCircle,
  FaInfoCircle,
  FaTruck,
  FaTrain,
  FaBolt,
  FaIndustry, // Pengganti FaConveyorBelt
  FaSun,
  FaCloudRain,
  FaSmog,
  FaSnowflake,
  FaRoad,
  FaTachometerAlt,
  FaBan,
  FaDollarSign,
  FaPhone,
  FaEnvelope,
  FaLock,
  FaEye,
  FaEyeSlash,
  FaPlus,
  FaEdit,
  FaTrash,
  FaSearch,
  FaFilter,
  FaSort,
  FaArrowLeft,
  FaArrowRight,
  FaHome,
  FaCog,
  FaBell,
  FaQuestionCircle,
  FaGlobe,
  FaMapMarkerAlt,
  FaWeightHanging,
  FaExchangeAlt,
  FaClock,
  FaTools,
  FaShieldAlt,
  FaDatabase,
  FaServer,
  FaNetworkWired,
  FaUsers,
  FaWarehouse,
  FaAnchor,
  FaCar,
  FaPlane,
  FaBicycle,
  FaWalking,
  FaUmbrella,
  FaWind,
  FaTemperatureHigh,
  FaCloud,
  FaCloudSun,
  FaMoon,
  FaStar,
  FaHeart,
  FaBookmark,
  FaDownload,
  FaUpload,
  FaPrint,
  FaSave,
  FaUndo,
  FaRedo,
  FaCopy,
  FaPaste,
  FaKey,
  FaWifi,
  FaCamera,
  FaVideo,
  FaMicrophone,
  FaVolumeUp,
  FaVolumeMute,
  FaHeadphones,
  FaMusic,
  FaGamepad,
  FaTv,
  FaMobile,
  FaLaptop,
  FaDesktop,
  FaKeyboard,
  FaMouse,
  FaHdd,
  FaMemory,
  FaMicrochip,
  FaSdCard,
  FaUsb,
  FaPlug,
  FaBatteryFull,
  FaBatteryHalf,
  FaBatteryEmpty,
  FaPowerOff,
  FaPlay,
  FaPause,
  FaStop,
  FaForward,
  FaBackward,
  FaStepForward,
  FaStepBackward,
  FaRandom,
  FaRepeat,
  FaVolumeDown,
  FaVolumeOff,
  FaEject,
  FaBus,
  FaTaxi,
  FaHelicopter,
  FaRocket,
  FaSatellite,
  FaParachuteBox,
  FaShuttleVan,
  FaTractor,
  FaTruckLoading,
  FaTruckMoving,
  FaTruckPickup,
  FaOilCan,
  FaGasPump,
  FaChargingStation,
  FaCarBattery,
  FaCarCrash,
  FaCarSide,
  FaTrailer,
  FaPallet,
  FaBoxOpen,
  FaBoxes,
  FaCubes,
  FaCube,
  FaBalanceScale,
  FaRuler,
  FaRulerHorizontal,
  FaMap,
  FaMapMarked,
  FaMapPin,
  FaCompass,
  FaCrosshairs,
  FaLocationArrow,
  FaStreetView,
  FaCloudShowersHeavy,
  FaCloudSunRain,
  FaPooStorm,
  FaSnowman,
  FaWind as FaWindWarning,
  FaFire,
  FaFireAlt,
  FaFireExtinguisher,
  FaFirstAid,
  FaAmbulance,
  FaHospital,
  FaHospitalAlt,
  FaHospitalSymbol,
  FaMedkit,
  FaPills,
  FaSyringe,
  FaBandAid,
  FaStethoscope,
  FaUserMd,
  FaUserNurse,
  FaNotesMedical,
  FaFileMedical,
  FaFileMedicalAlt,
  FaReceipt,
  FaCreditCard,
  FaMoneyBill,
  FaMoneyBillWave,
  FaMoneyCheck,
  FaChartLine,
  FaChartPie,
  FaChartArea,
  FaDonate,
  FaPiggyBank,
  FaWallet,
  FaGem,
  FaCrown,
  FaAward,
  FaTrophy,
  FaMedal,
  FaCertificate,
  FaGraduationCap,
  FaUserGraduate,
  FaUserTie,
  FaUserAstronaut,
  FaUserNinja,
  FaUserSecret,
  FaUserShield,
  FaUserTag,
  FaUserCheck,
  FaUserTimes,
  FaUserPlus,
  FaUserMinus,
  FaUserEdit,
  FaUserClock,
  FaUserCog,
  FaUserLock,
  FaUserUnlock,
  FaUserSlash,
  FaUserAlt,
  FaUserFriends,
  FaUserCircle,
  FaIdCard,
  FaIdCardAlt,
  FaAddressCard,
  FaPhoneAlt,
  FaPhoneSquare,
  FaPhoneVolume,
  FaEnvelopeOpen,
  FaPaperPlane,
  FaInbox,
  FaArchive,
  FaReply,
  FaReplyAll,
  FaShareSquare,
  FaShareAlt,
  FaExternalLinkAlt,
  FaLink,
  FaUnlink,
  FaQrcode,
  FaBarcode,
  FaShoppingCart,
  FaShoppingBag,
  FaShoppingBasket,
  FaStore,
  FaStoreAlt,
  FaTag,
  FaTags,
  FaGift,
  FaUtensils,
  FaCoffee,
  FaGlassCheers,
  FaBeer,
  FaConciergeBell,
  FaBellSlash,
  FaCalendar,
  FaCalendarCheck,
  FaCalendarDay,
  FaCalendarMinus,
  FaCalendarPlus,
  FaCalendarTimes,
  FaCalendarWeek,
  FaHourglass,
  FaHourglassEnd,
  FaHourglassHalf,
  FaHourglassStart,
  FaStopwatch,
  FaHistory,
  FaBusinessTime,
  FaBriefcase,
  FaSuitcase,
  FaSuitcaseRolling,
  FaPassport,
  FaVirus,
  FaVirusSlash,
  FaHeadSideCough,
  FaHeadSideMask,
  FaHandsWash,
  FaHandSparkles,
  FaHandHoldingHeart,
  FaHandHolding,
  FaHandPaper,
  FaHandPeace,
  FaHandPointDown,
  FaHandPointLeft,
  FaHandPointRight,
  FaHandPointUp,
  FaHandPointer,
  FaHandRock,
  FaHandScissors,
  FaHandSpock,
  FaThumbsUp,
  FaThumbsDown,
  FaPeace,
  FaGrin,
  FaGrinBeam,
  FaGrinHearts,
  FaGrinSquint,
  FaGrinStars,
  FaGrinTears,
  FaGrinTongue,
  FaGrinWink,
  FaKiss,
  FaKissBeam,
  FaLaugh,
  FaLaughBeam,
  FaMeh,
  FaMehBlank,
  FaMehRollingEyes,
  FaSadCry,
  FaSadTear,
  FaSmile,
  FaSmileBeam,
  FaSmileWink,
  FaSurprise,
  FaTired,
  FaAngry,
  FaDizzy,
  FaFlushed,
  FaFrown,
  FaFrownOpen,
  FaGrimace,
  FaRegCircle,
  FaRegMoon,
  FaRegSun,
  FaRegSnowflake,
  FaRegCloud,
  FaRegMeh,
  FaRegSmile,
  FaRegFrown,
  FaRegTimesCircle,
  FaRegCheckCircle,
  FaRegQuestionCircle,
  FaRegInfoCircle,
  FaRegExclamationCircle,
  FaRegExclamationTriangle,
  FaRegFlag,
  FaRegBookmark,
  FaRegCalendar,
  FaRegClock,
  FaRegComment,
  FaRegCommentAlt,
  FaRegComments,
  FaRegFile,
  FaRegFileAlt,
  FaRegFolder,
  FaRegFolderOpen,
  FaRegImage,
  FaRegImages,
  FaRegNewspaper,
  FaRegSave,
  FaRegWindowClose,
  FaRegWindowMaximize,
  FaRegWindowMinimize,
  FaRegWindowRestore
} from 'react-icons/fa';

export const APP_NAME = import.meta.env.VITE_APP_NAME || 'Mine & Shipping Planner';
export const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:9000/api';

export const ROLES = {
  MINE_PLANNER: 'mine_planner',
  SHIPPING_PLANNER: 'shipping_planner'
} as const;

export const ORDER_STATUS = {
  CREATED: 'Created',
  SCHEDULED: 'Scheduled',
  IN_TRANSIT: 'In Transit',
  COMPLETED: 'Completed',
  CANCELLED: 'Cancelled'
} as const;

export const SCHEDULE_STATUS = {
  PLANNED: 'Planned',
  ONGOING: 'Ongoing',
  COMPLETED: 'Completed',
  DELAYED: 'Delayed',
  CANCELLED: 'Cancelled'
} as const;

export const TRANSPORT_MODES = [
  'Truck',
  'Ship',
  'Train',
  'Barge',
  'Conveyor'
];

export const CARGO_TYPES = [
  'Coal',
  'Iron Ore',
  'Copper Ore',
  'Gold Ore',
  'Bauxite',
  'Nickel Ore',
  'Limestone',
  'Sand',
  'Gravel'
];

export const WEATHER_CONDITIONS = [
  'Clear',
  'Rainy',
  'Storm',
  'Foggy',
  'Snowy'
];

export const ROAD_CONDITIONS = [
  'Good',
  'Moderate',
  'Bad'
];

export const COLORS = {
  primary: '#6a3fb5',
  primaryLight: '#8a5fd3',
  primaryDark: '#4b2d8a',
  secondary: '#f6c94b',
  secondaryLight: '#f8d97a',
  secondaryDark: '#d4ad30',
  background: '#ffffff',
  backgroundSecondary: '#f9f9ff',
  text: '#222222',
  textLight: '#666666',
  border: '#e6e6f2',
  success: '#10b981',
  error: '#ef4444',
  warning: '#f59e0b',
  info: '#3b82f6'
};

export const ICONS = {
  LOGO: FaHardHat,
  MINE_PLANNER: FaHardHat,
  SHIPPING_PLANNER: FaShip,
  ORDER: FaBox,
  SCHEDULE: FaCalendarAlt,
  DASHBOARD: FaChartBar,
  USER: FaUser,
  LOGOUT: FaSignOutAlt,
  CLOSE: FaTimes,
  ERROR: FaExclamationTriangle,
  SUCCESS: FaCheckCircle,
  INFO: FaInfoCircle,
  TRANSPORT: {
    TRUCK: FaTruck,
    SHIP: FaShip,
    TRAIN: FaTrain,
    BARGE: FaShip, // Barge bisa diwakili dengan Ship
    CONVEYOR: FaIndustry // Ganti ConveyorBelt dengan Industry
  },
  WEATHER: {
    CLEAR: FaSun,
    RAINY: FaCloudRain,
    STORM: FaBolt,
    FOGGY: FaSmog,
    SNOWY: FaSnowflake
  },
  ROAD: {
    GOOD: FaTachometerAlt,
    MODERATE: FaRoad,
    BAD: FaBan
  },
  FINANCE: FaDollarSign,
  CONTACT: {
    PHONE: FaPhone,
    EMAIL: FaEnvelope
  },
  SECURITY: FaLock,
  VISIBILITY: {
    SHOW: FaEye,
    HIDE: FaEyeSlash
  },
  ACTIONS: {
    ADD: FaPlus,
    EDIT: FaEdit,
    DELETE: FaTrash,
    SEARCH: FaSearch,
    FILTER: FaFilter,
    SORT: FaSort,
    BACK: FaArrowLeft,
    NEXT: FaArrowRight,
    HOME: FaHome,
    SETTINGS: FaCog,
    NOTIFICATION: FaBell,
    HELP: FaQuestionCircle,
    GLOBE: FaGlobe,
    LOCATION: FaMapMarkerAlt,
    WEIGHT: FaWeightHanging,
    EXCHANGE: FaExchangeAlt,
    TIME: FaClock,
    TOOLS: FaTools,
    SHIELD: FaShieldAlt,
    DATABASE: FaDatabase,
    SERVER: FaServer,
    NETWORK: FaNetworkWired,
    USERS: FaUsers,
    WAREHOUSE: FaWarehouse
  }
} as const;

export const getTransportIcon = (mode: string): IconType => {
  const modeLower = mode.toLowerCase();
  if (modeLower.includes('truck')) return ICONS.TRANSPORT.TRUCK;
  if (modeLower.includes('ship') || modeLower.includes('barge')) return ICONS.TRANSPORT.SHIP;
  if (modeLower.includes('train')) return ICONS.TRANSPORT.TRAIN;
  if (modeLower.includes('conveyor')) return ICONS.TRANSPORT.CONVEYOR;
  return ICONS.TRANSPORT.TRUCK;
};

export const getWeatherIcon = (condition: string): IconType => {
  const conditionLower = condition.toLowerCase();
  if (conditionLower.includes('clear')) return ICONS.WEATHER.CLEAR;
  if (conditionLower.includes('rain')) return ICONS.WEATHER.RAINY;
  if (conditionLower.includes('storm')) return ICONS.WEATHER.STORM;
  if (conditionLower.includes('fog')) return ICONS.WEATHER.FOGGY;
  if (conditionLower.includes('snow')) return ICONS.WEATHER.SNOWY;
  return ICONS.WEATHER.CLEAR;
};

export const getRoadIcon = (condition: string): IconType => {
  const conditionLower = condition.toLowerCase();
  if (conditionLower.includes('good')) return ICONS.ROAD.GOOD;
  if (conditionLower.includes('moderate')) return ICONS.ROAD.MODERATE;
  if (conditionLower.includes('bad')) return ICONS.ROAD.BAD;
  return ICONS.ROAD.MODERATE;
};